name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            libssl-dev \
            libffi-dev \
            libsqlite3-dev \
            libncurses5 \
            libncurses5-dev \
            libtinfo5

      - name: Install buildozer + p4a
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36 virtualenv
          pip install buildozer python-for-android

      - name: Add pip user bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build debug APK
        run: |
          buildozer init || true
          buildozer android debug -v

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: bin/*.apk
