name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install APT packages
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip openjdk-17-jdk

      - name: Install python tools (buildozer)
        run: |
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user cython virtualenv buildozer

      - name: Ensure pip user bin on PATH for this job
        env:
          PATH: ${{ runner.home }}/.local/bin:${{ env.PATH }}
        run: echo "Using PATH=$PATH"

      - name: Initialize & Build debug APK
        env:
          PATH: ${{ runner.home }}/.local/bin:${{ env.PATH }}
        run: |
          # ensure buildozer config exists
          buildozer init || true
          # build (this can take long the first time)
          buildozer android debug -v
        working-directory: ${{ github.workspace }}

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: bin/*.apk
