name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            libssl-dev \
            libffi-dev \
            libsqlite3-dev \
            libncurses6 \
            libncurses-dev \
            libtinfo6 \
            wget

      - name: Install buildozer + p4a
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36 virtualenv
          pip install buildozer python-for-android

      - name: Add pip user bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Android cmdline-tools & SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
          
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Accept licenses & Install build-tools
        run: |
          sdkmanager --version
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" \
            "platforms;android-31" \
            "build-tools;30.0.3"

          echo ">>> Checking aidl in build-tools"
          ls -l $HOME/android-sdk/build-tools/30.0.3 || true
          ls -l $HOME/android-sdk/build-tools/30.0.3/aidl* || true

          # Xuất env ép Buildozer phải thấy aidl
          echo "PATH=$HOME/android-sdk/build-tools/30.0.3:$PATH" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
          echo "ANDROIDAPI=31" >> $GITHUB_ENV
          echo "ANDROIDNDKVER=r25b" >> $GITHUB_ENV
          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "AIDL=$HOME/android-sdk/build-tools/30.0.3/aidl" >> $GITHUB_ENV

      - name: Build debug APK
        run: |
          buildozer init || true
          buildozer android debug -v

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: |
            bin/**/*.apk
            *.apk
